export const GAME_CONFIG = {
    TICK_RATE: 20,
    ROOM_WIDTH: 800,
    ROOM_HEIGHT: 600,
    MIN_ROOMS: 5,
    MAX_ROOMS: 10,
    TRANSITION_PADDING: 15,
    SPAWN_PADDING: 100,
    MIN_ENEMIES_PER_ROOM: 1,
    MAX_ENEMIES_PER_ROOM: 3,
};